### ISSUE TITLE
LoadingExperience and enhanced_lighthouse

### ISSUE THREAD

**Issue by danielkupka** [Leszek-Sieminski/pagespeedParseR#3] opened 2019-07-03 19:08 UTC
Hi Leszek,

cool package. Thanks for your efforts on this.

Some things I noticed, when pulling the raw data from lighthouse (v5): 

**- LoadingExperience not complete**
It just shows the initial_url but not other variables under this item. 

Here a copy of from the API reference:
  "loadingExperience": {
    "id": string,
    "metrics": {
      (key): {
        "percentile": integer,
        "distributions": [
          {
            "min": integer,
            "max": integer,
            "proportion": double
          }
        ],
        "category": string
      }
    },
    "overall_category": string,
    "initial_url": string
  },

- Enhanced lighthouse
I cannot get additional data points when setting enhanced_lighthouse = T
Can you confirm that? 

Thanks a lot!

Best,

Daniel

**Comment by Leszek-Sieminski** [comment] 2019-07-03 20:13
Hi Daniel,

enhanced Lighthouse parameter was experimental and behaved in a rather unstable way - it is temporarily switched off until I develop something more reliable.

I may be wrong but loading experience is not an audit but a data created in Chrome User Reports. Not sure. Could you please provide a version of package that you use, a reproducible code sample, and a .RData file with your objects (list od data frame) with function output?

**Comment by Leszek-Sieminski** [comment] 2019-07-05 16:51
Hi Daniel,

I have just updated the package to 0.3.0.9000 (dev) version. Now download_lighthouse() function will has built-in "enhanced_lighthouse" thus providing much more data (hundreds/thousands of columns). Try it! You will find more details about it in README.md file and in function's documentation. 

The "loadingExperience" you asked about will be present in the new Lighthouse reports. However, you must remember that this information comes from CrUx:
![1](https://user-images.githubusercontent.com/32634801/60735873-3f077280-9f55-11e9-87d2-15f698962e44.png)

This basically means that columns about "loadingExperience" will be present in your report, but it is almost guaranteed that smaller websites will not return a score, because only large websites are covered by CrUx.

Hope you will find it helpful :) If you happen to have any questions, don't hesitate to write.

Closing the issue.

**Closed as completed by Leszek-Sieminski** 2019-07-05 16:51 UTC
